### ISSUE TITLE
Two do statements with same continue target provokes segmentation fault

### ISSUE THREAD

**Issue by carlobertolli** [llvm-flang/flang-old#15]
Input program:

```
  subroutine add(A, B, C, N)
```

C
      DIMENSION A(N,N),B(N,N),C(N,N)
      DO 100 I=1,N
      DO 100 J=1,N
           A(I,J) = B(I,J) + C(I,J)
  100 CONTINUE
      return
      END

Call stack dump:

Program received signal SIGSEGV, Segmentation fault.
flang::Stmt::getStmtLabel (this=0x0) at /localhd/cbertol/src/tools/flang/include/flang/AST/Stmt.h:94
94    Expr *getStmtLabel() const { return StmtLabel; }
(gdb) up
#1  0x00000000116d93d8 in flang::CodeGen::CodeGenFunction::EmitStmt (this=0x3fffffffcca8, S=0x0) at /localhd/cbertol/src/tools/flang/lib/CodeGen/CGStmt.cpp:96

96    if(S->getStmtLabel())
(gdb) up
#2  0x00000000116dac44 in flang::CodeGen::CodeGenFunction::EmitDoStmt (this=0x3fffffffcca8, S=0x13011230) at /localhd/cbertol/src/tools/flang/lib/CodeGen/CGStmt.cpp:322

322   EmitStmt(S->getBody());

**Comment by carlobertolli** [comment]
Fixed by last commit.
